name: Deploy to Azure
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -f Dockerfile.tests -t code-challenge-test .
          docker run --name code-challenge-test-container code-challenge-test pytest -v test

      - name: Check test results
        run: |
          docker logs code-challenge-test-container
          docker wait code-challenge-test-container
          docker rm code-challenge-test-container

          exit $(docker inspect --format='{{.State.ExitCode}}' code-challenge-test-container)
