name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run tests
        run: docker build -f Dockerfile.tests -t code-challenge-test .
        
      - name: Run unit tests
        run: docker run code-challenge-test pytest

      - name: Check test status
        id: test-status
        run: echo "::set-output name=status::$(if [ ${{ steps.test.outcome }} == 'success' ]; then echo 'success'; else echo 'failure'; fi)"

      - name: Finish Workflow
        if: steps.test-status.outputs.status == 'success'
        run: echo "All tests passed successfully."
